package feijuca;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;

/*
 * Copyright 2017 joao.palmas.br.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

public class Principal extends javax.swing.JFrame {
    static ArrayList<Funcionario> funcionarios = new ArrayList<>();
    static ArrayList<Usuario> usuarios = new ArrayList<>();
    static Usuario u= null;
    static boolean statusLogin = false;
    private BufferedImage img;

    /**
     * Creates new form telaCaixa
     */
    public Principal() {
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension d = tk.getScreenSize();
        int largura = d.width;
        int altura = d.height;
        setPreferredSize(new Dimension(largura,altura-50));
        URL url = this.getClass().getResource("../img/logo.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
        gera();
        initComponents();
        login telaLogin = new login();
        tela.add(telaLogin);
        telaLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tela = new javax.swing.JDesktopPane(){
            private Image image;
            {
                try {
                    image = ImageIO.read(new URL("file:///C:/Users/pix01/Desenvolvimento/NetBeans/Feijuca/src/img/banner.png"));
                }
                catch (IOException e) {
                    e.printStackTrace();
                }
            }
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0, getWidth(), getHeight(), this);
            }

        };
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenuCaixa = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        btnMenuEstoque = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        btnMenuUsuarios = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Feijuca");

        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tela.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout telaLayout = new javax.swing.GroupLayout(tela);
        tela.setLayout(telaLayout);
        telaLayout.setHorizontalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                .addContainerGap(562, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        telaLayout.setVerticalGroup(
            telaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaLayout.createSequentialGroup()
                .addContainerGap(408, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        btnMenuCaixa.setText("Caixa");
        btnMenuCaixa.setEnabled(false);

        jMenuItem1.setText("Nova Venda");
        btnMenuCaixa.add(jMenuItem1);

        jMenuBar1.add(btnMenuCaixa);

        btnMenuEstoque.setText("Estoque");

        jMenuItem3.setText("Cadastrar Produto");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        btnMenuEstoque.add(jMenuItem3);

        jMenuBar1.add(btnMenuEstoque);

        btnMenuUsuarios.setText("Usuarios");
        btnMenuUsuarios.setEnabled(false);

        jMenuItem2.setText("Cadastrar");
        btnMenuUsuarios.add(jMenuItem2);

        jMenuBar1.add(btnMenuUsuarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tela, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ProdutoCadastro TelaProdutoCadastro = new ProdutoCadastro();
        tela.add(TelaProdutoCadastro);
        TelaProdutoCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    public void gera(){
        Funcionario f1 = new Funcionario(1,"Ana Beatriz", "111", "111", "1111-1111", "1111-1111", "um@um.com", "endereco1", "caixa");
        funcionarios.add(f1);
        Funcionario f2 = new Funcionario(2,"Carlos Eduardo", "333", "333", "3333-3333", "3333-3333", "tres@tres.com", "endereco3", "gerente");
        funcionarios.add(f2);
        Funcionario f3 = new Funcionario(2,"Eduardo Lima", "555", "555", "5555-5555", "5555-5555", "cinco@cinco.com", "endereco5", "chefe");
        funcionarios.add(f3);
        
        Usuario u1 = new Usuario(1, "Ana", "ana", "ana", f1.funcao,1, 1);
        usuarios.add(u1);
        Usuario u2 = new Usuario(2, "Carlos", "carlos", "carlos", f2.funcao,1, 2);
        usuarios.add(u2);
        Usuario u3 = new Usuario(3, "Eduardo", "eduardo", "eduardo", f3.funcao,1, 3);
        usuarios.add(u3);
        /*
        for (Funcionario f: funcionarios){
            System.out.println(f.toString());
        }
        for (Usuario u: usuarios){
            System.out.println(u.toString());
        }
        */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JMenu btnMenuCaixa;
    static javax.swing.JMenu btnMenuEstoque;
    static javax.swing.JMenu btnMenuUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    static javax.swing.JDesktopPane tela;
    // End of variables declaration//GEN-END:variables
}
